import { POST_INITIAL_STATE } from './constants'
import {
  FETCH_POST,
  LIKE_POST_SUCCESS,
  UNDO_LIKE_POST_SUCCESS,
  DELETE_POST_SUCCESS,
  SHARE_POST_SUCCESS,
  FETCH_COMMENTS,
  FETCH_MORE_COMMENTS,
  PUBLISH_COMMENT_SUCCESS,
  LIKE_COMMENT_SUCCESS,
  UNDO_LIKE_COMMENT_SUCCESS,
  EDIT_COMMENT_SUCCESS,
  DELETE_COMMENT_SUCCESS,
  CLEAR_POST,
  FETCH_COMMENT_REPLIES,
  ADD_COMMENT_REPLY,
  FOLLOW_PAGE_ON_POST_SUCCESS,
  LOADING_COMMENTS,
  LIKE_COMMENT_REPLY_SUCCESS,
  UNDO_LIKE_COMMENT_REPLY_SUCCESS,
  DELETE_COMMENT_REPLY_SUCCESS,
} from '../../types/postTypes'
import {
  fetchPost,
  likePost,
  undolikePost,
  deletePost,
  sharePost,
  fetchComments,
  fetchMoreComments,
  publishComment,
  likeComment,
  undolikeComment,
  editComment,
  deleteComment,
  fetchCommentReplies,
  addCommentReply,
  changePostType,
  loadingComments,
  likeCommentReply,
  undolikeCommentReply,
  deleteCommentReply,
} from './handlers'

const actionHandlers = {
  [FETCH_POST]: fetchPost,
  [LIKE_POST_SUCCESS]: likePost,
  [UNDO_LIKE_POST_SUCCESS]: undolikePost,
  [DELETE_POST_SUCCESS]: deletePost,
  [SHARE_POST_SUCCESS]: sharePost,
  [LOADING_COMMENTS]: loadingComments,
  [FETCH_COMMENTS]: fetchComments,
  [FETCH_MORE_COMMENTS]: fetchMoreComments,
  [PUBLISH_COMMENT_SUCCESS]: publishComment,
  [LIKE_COMMENT_SUCCESS]: likeComment,
  [UNDO_LIKE_COMMENT_SUCCESS]: undolikeComment,
  [EDIT_COMMENT_SUCCESS]: editComment,
  [DELETE_COMMENT_SUCCESS]: deleteComment,
  [CLEAR_POST]: deletePost,
  [FETCH_COMMENT_REPLIES]: fetchCommentReplies,
  [ADD_COMMENT_REPLY]: addCommentReply,
  [LIKE_COMMENT_REPLY_SUCCESS]: likeCommentReply,
  [UNDO_LIKE_COMMENT_REPLY_SUCCESS]: undolikeCommentReply,
  [DELETE_COMMENT_REPLY_SUCCESS]: deleteCommentReply,
  [FOLLOW_PAGE_ON_POST_SUCCESS]: changePostType,
}

export const postReducerConfig = {
  initialState: POST_INITIAL_STATE,
  actionHandlers,
}
